# Test High Availability with autoscaling
crds:
  keep: false

redis-ha:
  enabled: false

server:
  autoscaling:
    enabled: true
    minReplicas: 1

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 1
