apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: apicurio-registry
deploy:
  helm:
    releases:
      - name: apcrg
        chartPath: .
        wait: true
        setValues:
          e2e: true
        valuesFiles:
          - "test/e2e/{{.E2E_TEST}}/values.yaml"
        upgradeOnChange: false
        skipBuildDependencies: true
